/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package world.as500.rpgle.xtext.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class XRPGLEUiModule extends AbstractXRPGLEUiModule {
}
