/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package world.as500.rpgle.xtext.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class XRPGLEProposalProvider extends AbstractXRPGLEProposalProvider {
}
