/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package world.as500.rpgle.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class XRPGLERuntimeModule extends AbstractXRPGLERuntimeModule {
}
