/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package world.as500.rpgle.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XRPGLEStandaloneSetup extends XRPGLEStandaloneSetupGenerated {

	def static void doSetup() {
		new XRPGLEStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
